config/settings.py, numerique_gouv/admin.py, numerique_gouv/apps.py, numerique_gouv/models.py, numerique_gouv/tests.py, numerique_gouv/views.py
Créer une nouvelle app pour faire les modifications spécifiques au site numerique.gouv.fr
=> Add a new numerique_gouv app

numerique_gouv/templates/numerique_gouv/blocks/title.html
deletes a wrong class in title block
=> delete wrong class

poetry.lock, pyproject.toml
Scalingo build failed with an error, try to remove added dependencies
=> try to remove dependencies

numerique_gouv/templates/numerique_gouv/blocks/highlight_cards.html
ajoute un template manquant suite à un revert
=> ajoute un template manquant suite à un revert

numerique_gouv/templates/numerique_gouv/blocks/offers_organization.html, numerique_gouv/templates/numerique_gouv/offers_entry_page.html
Corrige les conditions pour faire en sorte d'afficher le tableau correctement même si toutes les cases ne sont pas remplies
=> corrige l'affichage du tableau d'organisation des pages d'offres

numerique_gouv/templates/numerique_gouv/offers_index_page.html
=> Fix les filtres

requirements.txt
=> add boto3 to requirements

blog/templates/blog/blog_entry_page.html, numerique_gouv/management/commands/import_numerique_pages.py, numerique_gouv/models.py, numerique_gouv/templates/numerique_gouv/blocks/card_vertical.html
=> mets à jour le script de migration et améliore l'index des actus

requirements.txt
add dj-database-url to requirements
=> add dj-database-url to requirements

numerique_gouv/templates/numerique_gouv/blog_index_page.html
Reverts numerique-gouv/numerique-gouv-cms#139
=> Revert "évite d'avoir deux titres sur les pages de blog"

content_manager/templates/content_manager/blocks/item_grid.html
=> fix d'une condition

numerique_gouv/templates/numerique_gouv/blocks/hub_pages_heading.html, numerique_gouv/templates/numerique_gouv/hub_pages.html
=> Ajoute un bouton pour descendre en bas de page sur les pages carrefours

numerique_gouv/templates/numerique_gouv/blocks/hub_pages_heading.html, numerique_gouv/templates/numerique_gouv/hub_pages.html
This reverts commit 6907c79828876ddbbedab726f280365dc07870ba, reversing changes made to 265098670bcad1bf41e075c1b334969a386bf5c6.
=> revert last PR

numerique_gouv/models.py, numerique_gouv/templates/numerique_gouv/blog_index_page.html
=> improve numerique catalog pages

content_manager/templates/content_manager/blocks/item_grid.html
=> override grid position

numerique_gouv/templates/numerique_gouv/blog_index_page.html
=> Mise en production

.github/workflows/ci-main.yml, content_manager/templates/content_manager/blocks/item_grid.html
2d34ea15246c155edefa67efcd316c37b7e6e2e0
=> Revert "Revert "override grid position""

numerique_gouv/templates/numerique_gouv/blog_entry_page.html, numerique_gouv/templates/numerique_gouv/blog_index_page.html, numerique_gouv/templates/numerique_gouv/event_entry_page.html, numerique_gouv/templates/numerique_gouv/hub_pages.html, numerique_gouv/templates/numerique_gouv/numerique_page.html, numerique_gouv/templates/numerique_gouv/offers_index_page.html, numerique_gouv/templates/numerique_gouv/products_index_page.html, numerique_gouv/templates/numerique_gouv/sitemap.html, templates/base.html
Certaines page avaient une balise titre non pertinente avec seulement le nom du site
correction et suppression d'un fichier qui faisait doublon avec le fichier head.html
=> Améliore le header des pages

.github/workflows/ci-main.yml, numerique_gouv/templates/numerique_gouv/blog_entry_page.html, numerique_gouv/templates/numerique_gouv/blog_index_page.html, numerique_gouv/templates/numerique_gouv/event_entry_page.html, numerique_gouv/templates/numerique_gouv/hub_pages.html, numerique_gouv/templates/numerique_gouv/numerique_page.html, numerique_gouv/templates/numerique_gouv/offers_index_page.html, numerique_gouv/templates/numerique_gouv/products_index_page.html, numerique_gouv/templates/numerique_gouv/sitemap.html, templates/base.html
=> Mise en production amélioration des headers

numerique_gouv/templates/numerique_gouv/blog_entry_page.html, numerique_gouv/templates/numerique_gouv/blog_index_page.html, numerique_gouv/templates/numerique_gouv/event_entry_page.html, numerique_gouv/templates/numerique_gouv/hub_pages.html, numerique_gouv/templates/numerique_gouv/numerique_page.html, numerique_gouv/templates/numerique_gouv/offers_index_page.html, numerique_gouv/templates/numerique_gouv/products_index_page.html, numerique_gouv/templates/numerique_gouv/sitemap.html, templates/base.html
fcd34cede79669d208fd18cf3b05a72ac4ba198c
=> Revert "Merge pull request #178 from numerique-gouv/pages-header"

numerique_gouv/templates/numerique_gouv/hub_pages.html
=> Update links in hub_pages.html
